version: '3.9'

## NOTE: use the script 'start-docker-compose' to run this 

services:

  mariadb-server:
    image: mariadb:10.6.13
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mariadb-server-vol:/var/lib/mysql
    networks:
      - auth-service-network

  # Helps visualise and manage what happens on maria db
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    depends_on:
      - mariadb-server
    environment:
      PMA_HOST: mariadb-server
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8180:80
    networks:
      - auth-service-network

  # will block until sql setup
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - phpMyAdmin
    command: mariadb-server:3306
    networks:
      - auth-service-network


  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1    
    ports:
      - 8181:8080
    # for the import we also need the --import-realm when importing
    command: -v start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: cmullaney
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: mariadb
      KC_DB_URL_HOST: mariadb-server
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_PORT: 3306
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
    # we add this part to import the keycloack json file
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    networks:
      - auth-service-network

networks:
  auth-service-network:

volumes:
  mariadb-server-vol: